const STATUS = {
  SUCCESS_REQUEST: 200,
  CREATION_REQUEST: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED_REQUEST: 401,
  USER_NOT_FOUND_REQUEST: 404,
  INTERNAL_SERVER_ERROR: 500,
};

module.exports = {
  STATUS,
};
